<?php

return [
    'sign_in' => " تسجيل الدخول",
    'sign_up' => " تسجيل جديد",
    'logout' => "تسجيل خروج",

    // Common
    'tweets' => "المنشورات",
    'field_required' => " هذه الخانة إلزامية",
    'sub_specialties_values' => "يرجى تحديد تخصص دقيق صحيح",
    'workshop' => 'جلسة',
    'workshop_by_title' => 'جلسة بعنوان',
    'submit' => 'ارسال',
    'save' => 'حفظ',
    'send_request' => 'إرسال الطلب',
    'posting' => 'انشر',
    'post' => 'نشر',
    'image' => 'صورة',
    'no_tweets' => "لم يتم العثور على منشورات",
    'error' => "خطأ",
    'delete' => 'حذف',
    'success' => "تمت العملية بنجاح",
    'failed' => " لم تتم العملية بنجاح ",
    'view_all' => "مشاهدة الكل",
    'follower' => "متابعون",
    'followers' => "متابعين",
    'following' => "متابعة",
    'more' => "المزيد",
    'loading' => 'يتم التحميل',
    'none' => "لا يوجد",
    'male' => "ذكر",
    'female' => "أنثى",
    'username' => "اسم المستخدم",
    'usernames' => "أسماء المستخدمين",
    'name' => "الاسم كامل",
    'email' => "البريد الالكتروني",
    'password' => "كلمة المرور",
    'confirm_password' => "تأكيد كلمة المرور",
    'phone' => "رقم الجوال (رقم الواتساب)",
    'phone_description' => "يرجى إدخال الرقم الخاص بكم والمربوط ببرنامج الواتساب لغرض إرسال تذكير بمواعيد حجوزاتكم بالمنصة (الرقم سوف يكون غير مرئي للمستخدمين)",
    'gender' => 'الجنس',
    'dob' => "تاريخ الميلاد",
    'country' => "الدولة",
    'city' => "المدينة",
    'specialties' =>  "التخصصات",
    'entity_specialties' =>  "مجال تخصص الجهة",
    'sub_specialists' =>  "التخصصات الدقيقة",
    'sub_specialties' =>  "التخصصات الدقيقة",
    'specialty' => "التخصص",
    'general' => "عام",
    'about' => "نبذة مختصرة",
    'timeline' => " المنشورات",
    'posts' => "منشورات",
    'snapchat' => "سناب شات",
    'linkedin' => "لينكد ان",
    'insta' => "انستقرام",
    'youtube' => "يوتيوب",
    'facebook' => "فيسبوك",
    'telegram' => "تيليغرام",
    'twitter' => "تويتر",
    'whatsapp' => "واتساب",
    'website' => "الموقع الالكتروني",
    'workshops' => "الجلسات",
    'current' => "حالياً",
    'ongoing' => 'تحت التنفيذ',
    'not_started' => "لم يبدأ بعد",
    'canceled' => 'تم الالغاء',
    'completed' => "مكتملة",
    'hold' => "قيد الانتظار",
    'unhold' => "رفع الانتظار",
    'this_minutes' => "(:minute) دقيقة",
    'participants' => "المشاركين",
    'no_data' => "لا تتوفر البيانات",
    'advisor' => " خدمات المنصة",
    'beneficiary' => "المستفيد",
    'beneficiary_name' => "اسم المستفيد",
    'beneficiary_account_number' => "رقم حساب المستفيد",
    'checkout' => "الدفع",
    'fill_form' => "ارجو تعبئة النموذج اولا.",
    'close' => "اغلاق",
    'requests' => "الطلبات",
    'accept' => "قبول",
    'decline' => "رفض",
    'accepted' => "تم القبول",
    'declined' => "مرفوض",
    'are_you_sure' => "هل انت متأكد؟",
    'yes' => "نعم",
    'no' => "لا",
    'start' => "ابدأ",
    'cancel' => "الغاء",
    'started' => "تم البدء",
    'stop' => "توقف",
    'expired' => "منتهي",
    'mark_complete' => "انتهت الجلسة",
    'calls' => "المكالمات",
    'back_to_home' => "العودة للصفحة الرئيسية",
    'back_to_outgoing_sessions' => "العودة لصفحة جلساتي",
    'date' => "التاريخ",
    'time' => "الوقت",
    'price' => "السعر",
    'charities' => "التبرعات",
    'from' => "من",
    'to' => "الى",
    'c_price' => "ر.س(:p)",
    'c_price_earning' => "(:p) ريال سعودي",
    'coupon_discount' => "كوبون خصم",
    'subtotal' => "الاجمالي",
    'vat_full' => "الضريبة",
    'platform_fees' => "رسوم المنصة",
    'total' => "الاجمالي",
    'total_plus_vat' => "اجمالي المبلغ + الرسوم",
    'tracker' => "التعقّب",
    'invite_free' => "تم دعوتك للانضمام مجاناً",
    'vat' => "الضريبة ((:vat)%)",
    'skip' => "تخطي",
    'previous' => "السابق",
    'next' => "التالي",
    'id' => "المعرّف",
    'word' => "كلمة",
    'action' => "الأوامر",
    'csv' => "CSV",
    'en_name' => "الاسم بالإنجليزي",
    'ar_name' => "الاسم بالعربي",
    'created_at' => "تاريخ الإنشاء",
    'updated_at' => "تاريخ التعديل",
    'coupon_code' => "رمز الكوبون",
    'type' => "النوع",
    'maximum_use' => "اعلى استخدام",
    'expiry_date' => "تاريخ الإنتهاء",
    'amount' => "السعر",
    'fixed' => "ثابت",
    'percentage' => "النسبة",
    'text' => "النص",
    'status' => "الحالة",
    'no_of_request' => "عدد الطلبات",
    'feed' => "رد",
    'specialty_en_name' => "التخصص بالانجليزية",
    'specialty_ar_name' => "التخصص بالعربية",
    'ip' => "Ip",
    'page' => "الصفحة",
    'user' => "المستخدم",
    'verification' => "التحقق",
    'verified' => "تم التحقق",
    'not_verified' => "لم يتم التحقق",
    'joined_at' => "الانضمام الى",
    'last_active' => "اخر نشاط",
    'subscriber' => "مشترك",
    'admin' => "ادارة",
    'dashboard' => "لوحة التحكم",
    'edit' => "تعديل",
    'users' => "المستخدمين",
    'feeds' => "ردود",
    'settings' => "الاعدادات",
    'coupons' => "كوبونات",
    'all_coupons' => "جميع الكوبونات",
    'add_coupon' => "إضافة كوبون",
    'all_charities' => "جميع التبرعات",
    'add_charity' => "إضافة جمعية خيرية",
    'blocked_words' => "الكلمات المحظورة",
    'all_words' => "جميع الكلمات",
    'add_new_word' => "اضف كلمة جديدة",
    'specialists' => "التخصصات",
    'all_specialists' => "جميع التخصصات",
    'add_new_specialists' => "إضافة تخصص جديد",
    'all_sub_specialists' => "إضافة تخصصات دقيقة",
    'add_new_sub_specialists' => "إضافة تخصص دقيق جديد",
    'language' => "اللغة",
    'support' => "الدعم",
    'customer_support' => "دعم العملاء",
    'device' => "جهاز",
    'notifications' => "التنبيهات",
    'account_notifications' => "تنبيهات الحساب",
    'search_history' => "نتائج البحث",
    'term' => "مصطلح",
    'feeds-with-blocked-word' => "المنشورات التي تحتوي على كلمات محظورة",
    'reviews' => "التقييمات",
    'review' => "التقييم",
    'zoom_call' => "المكالمات",
    'star' => "نجمة",
    'send' => "ارسال",
    'messages' => "الرسائل",
    'message' => "رسالة",
    'messaging' => "الارسال",
    'agree_terms_condition' => "أوافق على الشروط والاحكام",
    'terms_condition' => 'الشروط والاحكام',
    'answer' => "الرد",
    'answered' => "تم الرد",
    'you' => "انت",
    'active' => "نشط",
    'view' => "عرض التفاصيل",
    'book_now' => "احجز الان",
    'already_participated' => "تمت مشاركتك",
    'percentage_amount' => "كمية النسبة المئوية",
    'fixed_amount' => "سعر ثابت",
    'not_yet_rated' => "لم يقيم بعد",
    'rate_service' => "قم بتقييم هذه الخدمة",
    'entity_type' => "نوع الهوية",
    'entity_status' => "حالة الهوية",

    'owner' => "المالك",
    'conversation' => "المحادثة",
    'visit' => "زيارة",
    'count' => "عد",
    'join' => "انضم",
    'import_charities' => "ادخال جمعيات خيرية",
    'creator' => "صاحب العمل",
    'first_message' => "اول رسالة",
    'avg_rating' => "معدل التقييمات",
    'filter' => "فرز",
    'all' => "الكل",
    'coupon' => "كوبون",
    'my_earnings' => "ارباحي",
    'ready_to_transfer' => "جاهز للتحويل",
    'workshop_reminder' => "تذكير للانضمام لجلسة مجدولة",
    'call_reminder' => "تذكير للانضمام لمكالمة مجدولة",
    'explore' => "استكشف",
    'order_accepted' => "تم قبول الطلب",
    'order_rejected' => "الطلب مرفوض",
    'invoice' => "فاتورة",
    'approved' => "مقبولة",
    'incomplete' => "غير مكتملة",
    'pending' => "قيد الانتظار",
    'order' => "طلب",
    'call' => "مكالمة",
    'bookings' => "الحجوزات",
    'initialized' => "تم الإنشاء",
    'billings' => "الفواتير",
    'reports' => 'التقارير',
    'details' => "التفاصيل",
    'distribution' => "التوزيع",
    'all_orders' => "جميع الطلبات",
    'payment_details' => "تفاصيل الدفع",
    'charity_advisor_amount' => "حساب المستشار",
    'admin_amount' => "حساب الإدارة",
    'transaction_id' => "رقم العملية",
    'reset' => "إعادة ضبط ",
    'deleted' => "مسح",
    'search' => "بحث",
    'trending' => "المتداول الان ",
    'hashtags' => "هاشتاق",
    'category' => "التخصصات",
    'follow' => "متابعة",
    'unfollow' => "الغاء متابعة",
    'order_created' => "إنشاء طلب",
    'forgot_password' => "نسيت الرمز",
    'select_speciality' => "اختر التخصص",
    'select_sub_speciality' => "اختر التخصص الدقيق",
    'verify_account' => "توثيق الحساب",
    'done' => "تم",
    'liked_tweets' => "الاعجابات",
    'go_to_admin_panel' => "الذهاب الى صفحة التحكم",
    'invited' => "دعوة",
    'order_id' => "رقم الطلب",
    'select_charity' => "خيارات",
    'select_profit_proceed_type' => "خيارات",
    'conversation_completed' => "انتهت المحادثة",
    'logs' => "سجل",
    'submitting' => "ارسال الطلب",
    'workshop_canceled' => "ألغيت الجلسة",
    'workshop_invited' => "دعوة لحضور جلسة",
    'call_canceled' => "مكالمة ملغاة",
    'conversation_canceled' => "محادثة ملغاة",
    'call_reminder_subject' => "تذكير بالمكالمة",
    'workshop_reminder_subject' => "تذكير بالجلسة",
    'workshop_completed' => "انتهت الجلسة",
    'call_completed' => "انتهت المكالمة",
    'my_workshops' => "جلساتي",
    'my_calls' => "مكالماتي",
    'set_my_call' => "مكالماتي الواردة",
    'for_charity' => "متبرع بها للجمعية الخيرية",
    'not_for_charity' => "لحسابي الخاص",
    'my_messages' => "الرسائل الصادرة",
    'my_received_messages' => "الرسائل الواردة",
    'join_workshop' => "انضمام للجلسة",
    'slot_not_available' => "المقاعد ممتلئة",
    'join_call' => "انضمام للمكالمة",
    'reply_to_messages' => "الرد على الرسالة",
    'confirmed_amount' => "تأكيد المبلغ",
    'system_logs' => "سجل النظام",
    'session_tracker' => "متابعة الجلسات",
    'user_tracker' => "متابعة المستخدمين",
    'total_amount' => "المبلغ الاجمالي",
    'final_amount' => "المبلغ النهائي",
    'gateway_amount' => 'حساب بوابة الدفع',
    'charity' => "جمعية خيرية",
    'transferred' => "تم التحويل",
    'home' => "الصفحة الرئيسية",
    'latest_news' => "آخر الأخبار",
    'example' => "مثال",
    'transferred_to' => "التحويل الى",
    'please_wait' => "الرجاء الانتظار",
    'not_paid' => "لم يتم السداد بعد",
    'payment_status' => "حالة السداد",
    'find_more_workshops' => "الجلسات المتاحة للحجز",
    'my_following' => "متابعون",
    'bank_details_name' => "اسم البنك",
    'bank_details_account_number' => "رقم الحساب البنكي",
    'bank_details_bic_code' => "رقم الحساب: (:bic)",
    'refund_initiated' => "تم إنشاء حالة الاسترجاع",
    'refunded' => "استرجاع",
    'media' => "وسائط متعددة",
    'suspended' => "متعثر",
    'remember_me' => "تذكرني",
    'payment_method' => "طريقة الدفع",
    'export_csv' => "تصدير",
    'my_workshop' => "جلساتي",
    'set_workshop' => "طلبات الجلسات الواردة",
    'account_number' => "رقم الحساب",
    'is_expired' => "تم الاغلاق",
    'verify' => "توثيق",
    'user_suspended' => 'الحساب مُعلّق, يرجى التواصل مع الإدارة',
    'user_deactivated' => 'الحساب غير نشط, يرجى التواصل مع الإدارة',


    // Outer home
    'welcome_title' => "أهلا بك في تيلي ان",
    'welcome' => "مرحبا",
    'home_browse_specialty' => "استكشف المتخصصون في المجالات التي تهمك وتستطيع أيضا مشاركتنا خبراتك واهتماماتك",

    // Outer header
    'search_placeholder' => "البحث عن التخصصات او المنشورات",
    'copyright' => "Copyright © (:date) teleIN. All rights reserved",

    // Outer auth
    'reset_here' => "إعادة ضبط هنا",
    'forgot_password_auth' => "نسيت كلمة المرور؟",
    'login_title' => 'تسجيل الدخول',
    'dont_have_account' => 'ليس لدي حساب',
    'register_now' => 'سجل الان',
    'login' => "دخول",
    'terms_register' => 'بالضغط هنا أنت موافق على الشروط والأحكام للمنصة <a target="_blank" href="(:url)">الشروط والأحكام.</a>',
    'already_have_account' => 'هل لديك حساب هنا؟',
    'register' => "سجّل الان",
    'reset_password_heading' => "إعادة تعيين كلمة المرور",
    'change_mind' => "غيرت رأيك",
    'change_password_heading' => "إعادة تعيين كلمة المرور",
    'otp' => "ادخل الرمز المرسل الى بريدك الالكتروني",
    'verify_email_header' => "التحقق من بريدك الالكتروني",

    // Payment methods
    'visa' => "فيزا",
    'stc' => "اس تي سي باي",
    'free' => "مجاناً",
    'apple' => "ابل باي",

    // Verify OTP page
    'resend_otp' => "اعادة ارسال الرمز",
    'otp_sent' => "تم ارسال الرمز بنجاح",

    // Commented tweets
    'commented_tweets' => "الردود",

    // Message
    'message_expires_in' => "يجب الرد خلال (:time)",

    'success_change_avatar' => "تم تغيير صورة العرض بنجاح",
    'success_change_cover' => "تم تغيير الصورة الخلفية بنجاح",

    // Error 404
    'page_not_available_404' => 'هذه الصفحة غير موجودة',
    'error_text_404' => 'قد يكون الرابط غير صحيح او هذه الصفحة قد أزيلت. تأكد من استخدام الرابط الصحيح ',

    // Breadcrumb
    'advisor_breadcrumb' => "الذهاب الى صفحة مقدم الخدمة",
    'beneficiary_breadcrumb' => "الذهاب الى صفحة المستفيد",

    // Dashboard
    'dashboard_search_placeholder' => "ابحث هنا عن أسم المتخصص",


    // Charity Beneficiary
    'b_name' => "Beneficiary Name",
    'b_account_number' => "Beneficiary Account Number",
    'bank_bic_code' => "Beneficiary BIC Code",
    'address_line_1' => "Address Line 1",
    'address_line_2' => "Address Line 2",
    'address_line_3' => "Address Line 3",

    // Forgot Password
    'check_email_otp' => "الرجاء مراجعة البريد الالكتروني للحصول علي رمز التفعيل ",

    // To view full profile
    'view_full_profile' => 'لمعرفة المزيد عن هذا المستخدم يجب عليك تسجيل الدخول',

    // Explore
    'follow_best_advisors' => 'أستكشف المستخدمين حسب التخصصات',
    'follow_best_entities' => 'استكشف المستخدمين حسب الجهات المشاركة معنا',



    // Blocked
    'account_currently_blocked' => 'الحساب محظور حاليا',
    'please_contact' => 'الرجاء التواصل ((:البريد الالكتروني))' ,

    // Notifications
    'notification_feed.comment' => "<strong>(:name)</strong> يوجد رد على منشورك",
    'notification_feed.like' => "<strong>(:name)</strong> أعجاب على منشورك",
    'notification_follow' => "<strong>(:name)</strong> تابع حسابك",
    'notification_no_notifications' => "لا يوجد تنبيه.",
    'notification_no_orders' => "لا يوجد طلبات.",
    'notification_no_logs' => "لم يتم العثور على سجلات.",
    'notification_message.accepted' => "<strong>(:name)</strong> تمت الموافقة على رسالتك.",
    'notification_message.rejected' => "<strong>(:name)</strong> تم رفض طلب الرسالة.",
    'notification_message.completed' => "<strong>(:name)</strong> تم الرد على رسالتك.",
    'notification_workshop.completed' => "<strong>(:name)</strong> أكمل الجلسة التي شاركت فيها.",
    'notification_workshop.canceled' => "<strong>(:name)</strong> تم الغاء الجلسة",
    'notification_workshop.accepted' => "تمت الموافقة على الجلسة",
    'notification_workshop.rejected' => "تم رفض الموافقة على الجلسة",
    'notification_workshop.user_canceled' => "<strong>(:name)</strong> ألغى الجلسة",
    'notification_call.completed' => "<strong>(:name)</strong> أكمل المكالمة معك التي تم حجزها.",
    'notification_call.accepted' => "تم قبول المكالمة",
    'notification_call.rejected' => "تم رفض المكالمة",
    'notification_call.reminder' => "المكالمة على وشك ان تبدأ",
    'notification_call.canceled' => "تم الغاء الطلب المعلق للمكالمة",
    'notification_call.user_canceled' => "<strong>(:name)</strong> الغاء طلب المكالمة",
    'notification_call.request' => "<strong>(:name)</strong> أرسل إليك طلب مكالمة تيلي إن",
    'notification_call.request.resolved' => "لقد قام <strong>(:name)</strong> بإتاحة مكالمات حسب المواعيد التي تم طلبها, يرجى النقر لاستكمال الحجز",
    'notification_workshop.pending' => "<strong>(:name)</strong> انظم للجلسة الخاصة بك.",
    'notification_call.pending' => "<strong>(:name)</strong> يطلب حجز مكالمة.",
    'notification_message.pending' => "<strong>(:name)</strong> أرسل اليك رسالة.",
    'notification_workshop.reminder' => "الجلسة على وشك ان تبدأ.",

    'notification_workshop.invited' => "<strong>(:name)</strong> تم دعوتك للجلسة الخاصة به",
    'notification_workshop_auto.canceled' => "انتهت صلاحية هذه الجلسة.",
    'notification_message.reminder' => "لديك طلب رسالة معلق",
    'notification_message.canceled' => "طلب الرسالة قد ألغي",
    'notification_message.user_canceled' => "<strong>(:name)</strong> تم الغاء الرسالة",

    // Notification content
    'notification_workshop_cancel_coupon' => "Sorry for inconvenience, next time you can use coupon <strong>(:coupon)</strong> to get a discount.",
    'notification_workshop_pending' => "انظم <strong>(:name)</strong>",
    'notification_workshop_reminder' => "<strong>(:name)</strong>",
    'notification_workshop_about_to_start' => "لديك جلسة بعنوان (:title) مع (:name) ستبدأ بعد 15 دقيقة",
    'notification_call_about_to_start' => "لديك مكالمة تيلي إن مع (:name) ستبدأ خلال 5 دقايق",

    // Review Profile
    'review_profile_text' => " (:avg) من 5 ( (:total) تقييمات)",

    // Order cancel remarks
    'order_expired' => 'انتهت مدة الطلب',
    'order_advisor_canceled' => 'تم ألغاء الطلب من مقدم الخدمة',
    'order_admin_canceled' => 'تم ألغاء الطلب من الادارة',
    'order_admin_on_hold' => 'تم تعليق الطلب من الادارة',

    // Register Page
    'register_title' => "إنشاء حساب",
    'your_interest' => "اهتماماتك:",
    'cred_wrong' => "كلمة المرور خاطئة/البريد الالكتروني",

    'username_unique' => "تم اختيار هذا المعرف من مستخدم آخر",
    'username_limit' => "عدد حروف اسم المستخدم يجب ان يكون بين(:min) الى (:max) حرف",
    'email_unique' => "هذا البريد الالكتروني موجود سابقا",
    'email_pattern' => "يجب ان يكون البريد الالكتروني صحيح",

    'email_verification' => 'تأكيد البريد الالكتروني',
    'account_verification' => 'تأكيد الحساب',

    'email_token_invalid' => 'الرمز المدخل غير صحيح.',
    'email_token_limit' => 'الرمز المدخل غير صحيح.',

    // Header
    'menu_hello' => "مرحبا، (:name)",
    'menu_edit_profile' => "تعديل الملف الشخصي",
    'menu_edit_profile_desc' => "تعديل المعلومات الشخصية",
    'my_orders' => "طلباتي",
    'reservation_requests' => "الطلبات المعلقة",
    'account_settings' => "اعدادات الحساب",
    'workshop_cant_create_alert' => 'لكي تتمكن من الاستفادة من هذه المنصة لابد من اكمال الملف الشخصي, نرجو منك <a href="(:url)" class="alert-link">ادخال بياناتك الشخصية</a>. ( للمعلومية فأن روابط حساباتك في مواقع التواصل الاجتماعية الأخرى تعتبر اختيارية )',

    // left side menu
    'saved_feed' => "الاعجابات",
    'profile' => 'الملف الشخصي',
    'advisor_desc' => "الذهاب الى لوحة مقدم الخدمة.",
    'beneficiary_desc' => "الذهاب الى لوحة المستفيد.",

    // Feed page
    'create_post' => 'إنشاء منشور',
    'feed_textarea_post_error_title' => 'خطأ',
    'create_workshop_desc' => 'أنشئ الجلسة الخاصة بك',

    'feed_textarea_empty' => 'يجب ان تكتب شيئا قبل ان تنشره.',
    'feed_textarea_file_not_supported' => "Sorry, only (:supported) files are supported",
    'feed_char_limit_exceeded' => "يجب ان لا يتعدى محتوي المنشور (:limit) حرف",
    'no_hashtag_found' => "لا يوجد هاشتاق",
    'no_category_found' => "لا يوجد تصنيف",
    'upcoming_messaging' => 'الرسائل القادمة',

    // Workshop form

    'workshop_already_booked' => "تم حجز الجلسة مسبقا",
    'workshop_name' => "اسم الجلسة",
    'workshop_description' => "وصف الجلسة",
    'workshop_date' => 'تاريخ الجلسة',
    'workshop_time' => 'وقت الجلسة',
    'workshop_duration' => "مدة الجلسة (بالدقائق)",
    'workshop_price' => "السعر (سيتم إضافة رسوم المنصة على إجمالي المبلغ)",
    'workshop_capacity' => "عدد الحضور",
    'workshop_charity' => "الجمعية الخيرية (اختياري)",
    'workshop_invite' => "دعوة مقدم خدمة (اختياري)",
    'workshop_name_required' => "مطلوب كتابة اسم للجلسة",
    'workshop_name_max' => "نعتذر اسم الجلسة يجب ان لا يتعدى (:max) حرف",
    'workshop_desc_required' => "مطلوب كتابة وصف للجلسة",
    'workshop_date_required' => "مطلوب تحديد التاريخ للجلسة",
    'workshop_time_required' => "مطلوب تحديد الوقت للجلسة",
    'workshop_duration_required' => "مطلوب تحديد مدة الجلسة",
    'workshop_duration_should_number' => "لابد ان تحدد مدة الجلسة بالدقائق",
    'workshop_duration_invalid' => "دقيقة(:min)مدة الجلسة يجب ان تكون اكثر من",
    'workshop_price_required' => "مطلوب تحديد السعر للجلسة",
    'workshop_price_should_number' => "السعر يجب ان يكون رقماً",
    'workshop_price_invalid' => "السعر يجب ان يكون اعلى من صفر",
    'workshop_capacity_required' => "مطلوب تحديد عدد الحضور للجلسة",
    'workshop_capacity_should_number' => "عدد الحضور للجلسة يجب ان يكون رقماً",
    'workshop_capacity_invalid' => "(:min) الى (:max)العدد المسموح لحضور الجلسة يجب ان يكون بين ",
    'workshop_invite_invalid' => "لا يوجد مستخدم بهذا الاسم",
    'workshop_invite_error_self' => "لا تستطيع طلب دعوة لك.",
    'work_invite_cant_create'  => "لا تستطيع دعوة هذا المستخدم لحضور الجلسة.",
    'workshop_join_expired' => "نعتذر لا تستطيع الانضمام لهذه الجلسة",
    'you_cant_use_this_time_for_workshop' => "نعتذر هذا اقصى حد لعدد الحضور في هذا التوقيت, اذا اردت ان تزيد عدد الحضور نرجو تغيير وقت الجلسة",

    // workshop feed
    'workshop_feed_price' => "بإمكانك الحجز بهذا السعر (:price) ر.س",
    'workshop_feed_invited' => '<a href="(:profile_link)"><strong>@(:user)</strong></a> مدعو لحضور هذه الجلسة .',
    'workshop_feed_charity' => "سوف يتم تبرع بالمبلغ لصالح الجمعية الخيرية;(:charities)",
    'workshop_created' => "لقد أنشئت جلسة جديدة بنجاح",
    'feed_workshop_is_deleted' => " نعتذر هذه الجلسة ملغاة ",
    'feed_has_workshop' => "هذا المستخدم لدية جلسة <strong>(:name)</strong>",

    // feed Comment
    'comment_box_empty' => "بإمكانك إضافة رد هنا ",
    'total_comments' => '(:num) ردود',
    'load_more_comments' => 'تحميل المزيد من الردود',
    'write_comment' => ' اضف تعليقك هنا',
    'comment_box_max_limit' => "حرف  (:max)نعتذر لا تستطيع كتابة تعليق بأكثر من  characters long.",

    //Feed options
    'delete_feed' => 'مسح',
    'delete_feed_desc' => 'مسح هذا الرد',

    // New feed notification
    'new_feed_available' => "يوجد تعليق جديد لديك",

    //Profile Page
    'follow_success' => "انت الان تتابع هذا المستخدم",
    'unfollow_success' => "انت الان لا تتابع هذا المستخدم",
    'error_while_uploading' => "يوجد خطأ اثناء التحميل حاول مرة اخرى.",
    'cover_not_supported' => "هي المدعومة  (:supported)نعتذر فقط مسوغات ملفات",
    'change_cover' => "تغيير الصورة الخلفية",
    'change_avatar' => "تغيير الصورة العرض",
    'please_wait_cover' => "فضلا انتظر، يتم تغيير صورة ملفك الشخصي",
    'please_wait_avatar' => "فضلا انتظر، يتم تغيير خلفية ملفك الشخصي",
    'no_follower' => "لا يوجد متابعون الى الان",
    'no_following' => "لم تتابع احداً بعد",
    'book_a_call' => "احجز مكالمة",
    'book_a_workshop' => "احجز جلسة",
    'call_following_times_are_available' => "المكالمات متاحه في الأوقات التالية",

    // edit Profile
    'general_information' => "الملف التعريفي الخاص بك",
    'social_links' => 'روابط مواقع التواصل الاجتماعي الخاصة بك',
    'social' => 'التفاعلات على حسابك',
    'bank_details' => 'معلومات البنك (لتلقي أموالكم)',
    'iban_number' => "رقم الآيبان",
    'about_bio_placeholder' => "أكتب سيرتك الشخصية",
    'about_bio_placeholder_entity' => "أكتب وصف الجهة",
    'bio' => "الملف التعريفي",
    'about_achievements_placeholder' => "أكتب إنجازاتك",
    'achievements' => "الإنجازات",
    'location' => "الدولة/ المدينة",
    'change_password' => 'تغيير كلمة المرور',
    'current_password_not_match' => "كلمة مرور غير صحيحة.",
    'new_password_not_match' => "كلمة مرور غير متطابقة.",
    'select_a_country' => "اختر الدولة",
    'select_a_city' => "اختر المدينة",
    'enter_bank_details' => "ادخل معلومات البنك",
    'enter_beneficiary_name' => "ادخل اسم المستفيد",
    'enter_account_number' => "ادخل رقم الحساب(IBAN)",
    'enter_bic_code' => "البنكي BICادخل رمز ",
    'enter_bank_name' => "ادخل اسم البنك",
    'current_password' => "كلمة المرور الحالية",
    'new_password' => "كلمة المرور الجديدة",
    'verify_password' => "التحقق من كلمة المرور",
    'phone_invalid' => "الرجاء ادخال رقم اتصال صحيح ",
    'phone_unique' => "الرجاء ادخال رقم اتصال غير مستخدم",
    'snapchat_invalid' => "ادخل رابط سناب شات صحيح",
    'linkedin_invalid' => "ادخل رابط لينكد ان صحيح",
    'insta_invalid' => "ادخل رابط انستقرام صحيح",
    'youtube_invalid' => "ادخل رابط يوتيوب صحيح",
    'facebook_invalid' => "ادخل رابط فيسبوك صحيح",
    'telegram_invalid' => "ادخل رابط تيليغرام صحيح",
    'twitter_invalid' => "ادخل رابط تويتر صحيح",
    'website_invalid' => "ادخل رابط موقع صحيح",

    // Workshop Page
    'create_workshop' => "إنشاء جلسة",
    'find_workshops' => "البحث عن الجلسات",
    'find_workshops_search' => "البحث عن الجلسات - (:filter)",
    'workshop_not_exists' => "جلسة غير موجودة.",
    'capacity_exceed' => "اكتمل العدد المسموح للحضور لهذه الجلسة",
    'workshop_request_expired' => "انتهت مدة الطلب لهذه الجلسة",
    'workshop_waiting_approval' => "انتظار التأكيد",
    'workshop_join_not_started' => "الجلسة لم تبدء بعد, الرجاء اعد المحاولة في وقت الجلسة المحدد.",
    'workshop_join_preparing' => "الجلسة لم تبدء بعد, الرجاء اعد المحاولة في وقت الجلسة المحدد.",
    'workshop_join_completed' => "انتهت الجلسة.",
    'workshop_join_canceled' => "ألغيت الجلسة.",
    'workshop_cancel_placeholder' => "Insert a 100/100 coupon to cancel.",
    'search_workshop' => "البحث عن الجلسات بالاسم",

    // Calls
    'manage_calls' => "المكالمات القابلة للحجز",
    'find_calls' => "البحث عن المزيد من المكالمات",
    'find_calls_search' => "البحث عن المكالمات - (:filter)",
    'customize_calls' => "لطلب حجز موعد للاتصال مع (:filter)، قم بتحديد ثلاث اوقات مقترحه وسوف يتم تنبيهك في حال التأكيد",
    'booking_calls' => "بامكانك حجز موعد اتصال مع (:filter) بشكل اسرع حسب الاوقات المتاحه التالية",
    'create_call' => "إنشاء مكالمة",
    'back_to_manage_calls' => "العودة الى إنشاء مكالمة",
    'back_to_calls' => "العودة الى المكالمات",
    'call_price' => "السعر (سيتم إضافة رسوم المنصة على إجمالي المبلغ)",
    'call_slot_created' => "تم الإنشاء بنجاح",
    'call_request_created' => "تم إنشاء الطلب, سيصلك تنبيه حال موافقة المستشار",
    'call_slots_available_for' => "مكالمة متاحة بسعر <strong>(:price) SR</strong> في الوقت <strong>(:time)</strong>",
    'call_request_expired' => "انتهت صلاحية طلب المكالمة",
    'call_join_not_started' => " المكالمة لم تبدء بعد, الرجاء اعد المحاولة في وقت المكالمة المحدد.",
    'call_join_completed' => "انتهت المكالمة.",
    'call_join_canceled' => "ألغيت المكالمة.",
    'call_join_expired' => "عذراً لا تستطيع الانضمام الى هذه المكالمة مرة اخرى",
    'you_cant_use_this_time_for_call' => "نعتذر هذا التوقيت غير متاح, الرجاء تغيير التوقيت والمحاولة مرة أخرى.",
    'choose_suitable_appointments' => "يرجى اختيار ثلاقة أوقات مناسبة لكم لإجراء المكالمة",
    'schedule_the_following_appointments' => 'الرجاء اختيار الوقت المناسب لك وفق التواريخ والاوقات التي طلبها (<string>(:name)</string>) وتحديد سعر المكالمة.',
    'schedule_the_following_appointments_note' => '"للمعلوميه مدة المكالمه ١٥ دقيقه"',
    'call_request' => "طلب مكالمة",
    'call_request_resolved' => "تم معالجة طلب الاتصال",
    'date1' => "التاريخ الأول",
    'date2' => "التاريخ الثاني",
    'date3' => "التاريخ الثالث",
    'schedule' => "جدولة",

    // Messaging
    'manage_message_price' => "إعداد خدمة الرسائل",
    'back_to_messaging' => "العودة الى الرسائل",
    'messaging_price_should_number' => "السعر لابد ان يكون رقماً صحيحاً",
    'messaging_price_invalid' => "السعر لابد ان يكون اعلى من صفر",
    'price_updated' => "تم تحديث السعر",
    'message_modal_title' => "ارسال رسالة الى (:name)",
    'enable_messaging' => "تفعيل الرسائل",
    'write_your_message_first' => "اكتب رسالتك اولاً",
    'book_message_for' => 'بإمكانك ارسال رسالة الى <strong>(:name)</strong>',
    'messaging_warning' => "اذ لم يتم الرد على رسالتك من قبل هذا المستخدم خلال <strong>48 ساعة</strong> فأن المبلغ سوف يعود اليك.",
    'conversation_request_expired' => "لا تستطيع الرد على هذه المحادثة حيث ا الوقت المحدد للرد قد انتهى.",
    'conversation_expired' => "محادثتك قد انتهى الوقت المحدد للرد عليها وسوف يعود لك المبلغ المدفوع",
    'write_answer' => "تستطيع كتابة ردك هنا",
    'warning_before_message_answer' => "هل هذه هي إجابتك النهائية؟",

    // Request

    //Review
    'review_title_conversation' => "ما مدى رضاك على الخدمة المقدمة اليك من قبل هذا المستخدم <strong>(:name)</strong>?",
    'review_title_workshop' => " ما مدى رضاك على الخدمة المقدمة اليك من قبل هذا المستخدم <strong>(:name)</strong>?",
    'review_title_call' => " ما مدى رضاك على الخدمة المقدمة اليك من قبل هذا المستخدم <strong>(:name)</strong>?",
    'give_your_rating' => "قيم تجربتك لمشاركة نتيجتك مع الاخرين",
    'is_final_review' => "هل انت متأكد من هذا التقييم؟",
    'thank_you' => "شكراً لمشاركتنا تقييمك.",

    // Service related
    'service_time_over' => "عذراً لقد انتهت المدة المسموحة للاستفادة من هذه الخدمة ",
    'service_join_advisor_not_started' => "عذرًا ، يبدو أن المستشار قد تأخر ، يرجى الانتظار أو إذا لم يحضر المستشار ، يرجى الاتصال بالدعم.",
    'workshop_time_yet_not_started' => "عذرًا ، الجلسة لم تبدأ بعد ولكن يمكنك الدخول إليها قبل 5 دقائق من وقتها الفعلي",
    'call_time_yet_not_started' => "عذرًا ، لا يمكنك بدء هذه الخدمة إلا عندما يبدأ وقتها",
    'service_expire_reason' => "عذراً انتهى وقت الخدمة. وسوف تلغى تلقائياً خلال 24 ساعة وسوف يتم إعادة المبلغ اليكم.",
    'not_service_owner' => "عذرا يبدو انك لست مقدم الخدمة",

    // Checkout page
    'pay_with_apple_pay' => "ادفع عن طريق ابل باي",
    'pay_with_visa' => "ادفع عن طريق الفيزا او الماستر كارد",
    'pay_with_mada' => "ادفع عن طريق مدى",
    'pay_with_stc' => "ادفع عن طريق اس تي سي باي",
    'pay_now' => "ادفع الان (:price) ريال سعودي",
    'check_out_for' => "متابعة عملية الدفع للمستخدم: (:name)",
    'free_checkout' => "عملية الدفع مجانية",
    'checkout_invited_free_workshop' => "لقد تم دعوتك لحضور الجلسة مجاناً.",
    'checkout_success' => "تم الدفع بنجاح",
    'checkout_fail' => "فشلت عملية الدفع",
    'order_success' => "تم إنشاء طلبك بنجاح",
    'order_success_desc' => "شكراً لك, طلبك لهذه الخدمة تم بنجاح, نرجو منك الاطلاع على تفاصيل فاتورة الطلب.",
    'order_waiting_desc' => "الرجاء الانتظار قليلاً لضمان اتمام العملية بنجاح",
    'order_fail' => "عذراً يوجد خطأ في إنشاء هذا الطلب",
    'order_fail_desc' => "عذراً لم نستطيع تنفيذ عملية الدفع",
    'go_to_my_orders' => "الذهاب الى طلباتي",
    'checkout_wait_preparing' => "نرجو الانتظار حيث يتم تجهيز طلبك ليتم الانتقال للخطوة التالية",
    'apply_coupon_btn' => "+ استخدم الكوبون",
    'coupon_expired' => "نعتذر فقد انتهت صلاحية هذا الكوبون",
    'coupon_applied' => "هذا الكوبون <strong>(:coupon)</strong> قد تم تنفيذه",
    'select_a_payment_option' => "اختر الية الدفع المفضلة لديك ",
    'checkout_pay_title' => "اكمل عملية الدفع",
    'slot_full' => "عذرا قد اكتمل حجز المقاعد المحددة لهذه الجلسة .",
    'slot_full_badge' => "اكتمل عدد الحجوزات",
    'checkout_workshop_expired' => "لا تستطيع حجز هذه الجلسة حيث انتهت مدة الحجز عليها.",
    'checkout_call_expired' => " لا تستطيع حجز هذه المكالمة حيث انتهت مدة الحجز عليها.",

    // Coupons
    'total_use_count' => "Total use count: (:count)",
    'coupon_not_found' => "هذا الكوبون غير موجود, برجاء إدخال كوبون صحيح",
    'coupon_max_limit_reached' => "Sorry, this coupon has reached its max use limit",
    'coupon_100_required' => "Sorry, you need to add a 100/100 coupon to invite",

    // Invite
    'invite_user_desc' => "Please use comma separator to invite users. Eg: @username1, @username2",
    'invite_free_users' => "Invite free users",
    'invite_free_user' => "Invite free user",
    'invite_error_self' => "Sorry you cant not invite your self.",
    'invite_error_not_found' => "Sorry, some of the users are not found.",
    'invite_successful' => "Invited successfully",

    // Order page
    'order_request_for_workshop' => 'هذا المستخدم حجز جلسة  <strong>(:name)</strong>.',
    'order_request_for_call' => 'هذا المستخدم حجز مكالمة <strong>(:name)</strong>.',
    'order_request_for_conversation' => 'هذا المستخدم قد ارسل رسالة, <strong>(:name)</strong>.',

    // My order
    'my_orders_title' =>  "مجموع <strong>(:count)</strong> طلباتي",
    'ordered_on' => 'تم الطلب في <strong>(:date)</strong> عن <strong class="text-info">(:price)ريال سعودي</strong>',
    'your_order_id' => "رقم الطلب #(:id)",
    'user_cant_cancel_anymore' => "لا يمكنك الغاء هذا الطلب",

    // View order page
    'ordered_on_view' => 'تم هذا الطلب في <strong>(:date)</strong>',
    'payment_initiated_on_view' => ' تم الدفع في (:date) بمبلغ <strong>(:price)ريال سعودي</strong>',

    // Logs
    'earning_log_order_declined' => ' (:entity_type) الطلب ملغي ويجب إعادة مبلغ (:amount)SR <a href="(:link)">راجع الطلب</a>',
    'earning_log_order_accepted' => ' (:entity_type)الطلب مقبولة بمبلغ  (:amount)SR <a href="(:link)">راجع الطلب</a>',
    'earning_log_order_pending' => '(:userLink) اتم طلب جديد (:entity_type) <a href="(:link)">راجع الطلب</a>',
    'earning_log_order_canceled' => 'An (:entity_type) الطلب ملغي ويجب إعادة مبلغ (:amount)SR <a href="(:link)">راجع الطلب</a>',
    'earning_log_order_completed' => 'An (:entity_type) الطلب مقبولة بمبلغ (:amount)SR <a href="(:link)">راجع الطلب</a>',

    // Search
    'whats_trending' => "المواضيع المتداولة",
    'searching_for' => "البحث عن \"(:term)\"",
    'no_search_term' => "لم يتم توفير مصطلح للبحث",

    // Instruction modal

    // Email subjects
    'support_email_title' => "لديك بريد الكتروني جديد من  (:email)",

    // Admin billing
    'change_status' => "تغيير الحالة",
    'order_status_change_warning' => "بمجرد تغيير الحالة الى  <strong>الغاء</strong> فانك لا تستطيع العودة مجدداً, لذلك تأكد قبل التنفيذ ",

    // New version changes
    'privacy_policy' => 'السياسة والخصوصية',
    'terms_of_use' => 'سياسة الاستخدام',
    'view_personal_profile_details' => "عرض الحساب الشخصي",
    'manage_your_account_parameters' => "التحكم في الملف الشخصي",
    'sign_out' => "تسجيل خروج",
    'write_something_here' => 'اكتب ما تريد مشاركتنا به هنا',

    'c_views' => '(:num) المشاهدات',
    'c_likes' => '(:num) الاعجابات',
    'view_more_request' => 'عرض المزيد من الطلبات',
    'cancelled_expired' => 'تم الاغلاق',
    'stats' => 'المؤشرات',
    'message_stats' => 'حالة الرسالة',
    'call_stats' => 'حالة المكالمة',
    'workshop_stats' => 'حالة الجلسات',
    'block' => 'حظر',
    'unblock' => 'رفع الحظر',
    'please_upload_csv' => 'Please upload a csv file',
    'please_upload_jpg_png' => 'الرجاء ارفاق ملف بصيغة jpg او png',
    'please_select_a_img' => 'الرجاءاختيار صورة',
    'view_image' => 'عرض الصورة',
    'personal_improvement' => 'Personal Improvement',

    'call_duration_details' => 'مدة المكالمة(:duration) دقيقة',
    'search_more_workshop' => "البحث عن الجلسات بالاسم",
    'back_to_my_account' => "الرجوع الى الملف الشخصي",
    'entity_id' => "Entity Id",
    'ref_id' => "المرجع: (:id)",
    'ref' => "Ref",
    'share' => "مشاركة",

    'my_profile' => "الملف الشخصي",
    'header_my_messages' => "رسائلي",
    'header_my_calls' => "مكالماتي",
    'header_my_workshops' => "جلساتي",

    'feed_sure' => 'هل أنت متأكد من أنك تريد حذف هذا الموجز؟',
    'explore_professionals_interest' => 'Explore professionals in you areas of interest',
    'share_experience_interest' => 'You can share your	experiences	and	interests with everyone	too',

    // New changes
    'likes' => 'الإعجابات',
    'comments' => 'تعليقات',
    'close_modal' => "اغلاق",
    'filter_workshop' => "بحث",
    'following_profile' => "متابعون",
    'find_more_workshops_nav' => "الجلسات المتاحة للحجز",
    'header_my_workshops_nav' => "جلساتي",
    'workshop_min_time_error' => "يجب أن يكون الوقت مساويًا أو أكبر من (:min)",
    'already_scheduled_workshop' => "لايمكن إنشاء جلسات متقاطعة, لديك جلسة فعلاً ستبدأ في (:date) برجاء أختيار فترة أخرى",

    // Instruction
    'instruction_header' => 'اهلا بك في منصة تيلي ان للتواصل الاجتماعي',

    'instruction_desc_1' => 'بامكانك استثمار وقتك معنا ومشاركتنا تجاربك وخبراتك أياً كان تخصصك او اهتمامك تعليمي - تقني - ترفيهي اوحتى مناقشة افكار عامة ثقافات اخرى',
    'instruction_desc_2' => 'حيث تتيح لك المنصة استقبال مكالمات ورسائل وكذلك إنشاء جلسات نقاشية بمقابل مالي تحدده يزيد من ارباحك الشهريةوفي نفس الوقت تستطيع طلب مكالمات وارسال الرسائل وكذلك حضور جلسات مع من تريد التواصل معهم في المنصة',
    'instruction_desc_3' => 'منصة تيلي ان المنصة التي تحقق لك الارباح وتسهل لك الوصول لاصحاب الخبرات والاهتمامات والتواصل معهم',

    'faq' => 'الأسئلة الشائعة',
    'terms_of_service' => 'شروط الخدمة',
    'change_language' => "انقر لتغيير اللغة",

    'after_deducting_service_fee' => "بعد خصم رسوم الخدمة",

    // Waiting room
    'waiting_room' => 'غرفة الانتظار',
    'waiting_for_host_to_start_this_session' => 'في انتظار المضيف لبدء هذه الجلسة',
    'waiting_for_host_to_start_this_call' => 'في انتظار المضيف لبدء هذه الجلسة',
    'time_remaining_to_start_session' => 'الوقت المتبقي على الموعد المحدد لبدء هذه الجلسة هو:',
    'time_remaining_to_start_call' => 'الوقت المتبقي على الموعد المحدد لبدء هذه المكالمة هو:',
    'waiting_for_the_host_to_start_the_session' => 'في انتظار صاحب الجلسة ان يبدء كي تتمكن من الانضمام',
    'waiting_for_the_host_to_start_the_call' => 'في انتظار صاحب المكالمة ان يبدء كي تتمكن من الانضمام',
    'you_have_session_with_advisor' => 'لديك جلسة سوف تبدأ مع:',
    'you_have_session_with_participant' => 'لديك جلسة سوف تبدأ قريباً',
    'you_have_call_with_advisor' => 'لديك مكالمة سوف تبدأ مع:',
    'you_have_call_with_participant' => 'لديك مكالمة سوف تبدأ قريباً',

    // WhatsApp notifications
    "workshop_booked" => 'قد تم تسجيلك لحضور الجلسة بنجاح تحت عنوان ":workshop_title" 
سوف نقوم بإرسال رابط حضور هذه الجلسة قبل موعدها ب ١٥ دقيقه هنا وعبر الايميل 
اضافة موعد وتفاصيل الجلسة في التقويم اضغط هنا',

    'value_greater_than' => 'برجاء إدخال قيمة أكبر من (:value)',
    'value_less_than' => 'برجاء إدخال قيمة أصغر من (:value)',

    'individual' => 'فرد',
    'entity' => 'مؤسسة / شركة / جهة حكومية / جهة خيرية',
    'entities' => 'الجهات',
    'all_entities' => 'جميع الجهات',
    'add_entity' => 'إضافة مؤسسة',
    'your_entity' => 'الجهة المنتسب إليها',
    'select_an_entity' => 'أختر جهة من الجهات المشاركة في منصة تيلي إن',
    'associates_profile' => 'المنتسبين',
    'no_associate' => 'لايوجد منتسبين إلى الآن',
    'associates' => 'المنتسبين',

    'order_status' => 'حالة طلب الحجز',
    'service_status' => 'حالة الخدمة',
    'service_id' => 'معرف الخدمة',
    'service_type' => 'نوع الخدمة',
    'service_name' => 'اسم الخدمة',
    'select_a_user' => 'أختر مستخدم',
    'select_workshop' => 'أختر جلسة',

    'inv_title' => 'فاتورة اشتراك',
    'inv_company_title' => 'منصة تيلي إن',
    'inv_registration_no' => 'رقم السجل التجاري',
    'inv_invoice_to' => 'فاتورة إلى',
    'inv_invoice_no' => 'رقم الفاتورة',
    'inv_invoice_date' => 'تاريخ الفاتورة',
    'inv_sum' => 'المجموع',
    'inv_qty' => 'الكمية',
    'inv_fee' => 'الرسم',
    'inv_platform_fee' => 'رسوم المنصة',
    'inv_vat' => 'ضريبة القيمة المضافة',
    'inv_description' => 'الوصف',
    'inv_item' => 'البند',
    'inv_total' => 'الإجمالي',
    'inv_paid' => 'مدفوعة',
    'inv_amount_due' => 'المبلغ المستحق',
    'inv_discount_percentage' => 'الحسم',

    'incoming_notification' => 'تنبيه وارد',


    'Sat' => 'السبت',
    'Sun' => 'الأحد',
    'Mon' => 'الأثنين',
    'Tue' => 'الثلاثاء',
    'Wed' => 'الأربعاء',
    'Thu' => 'الخميس',
    'Fri' => 'الجمعة',

    'thanks_for_contacting_with_us' => 'نشكر لكم تواصلكم معنا, سيتم النظر في رسالتكم في أسرع وقت ممكن',
    'options' => 'خيارات',
    'profits_for' => 'ريع الأرباح',
    'available' => 'متوفر',
    'single_slot' => 'مكالمة واحدة',
    'many_slots' => 'مجموعة مكالمات ضمن مجال زمني',
    'from_time' => 'من',
    'to_time' => 'إلى',
    'no_results' => 'لاتوجد نتائج',
    'cropper_modal_title' => 'أقتصاص الصورة',
    'amount_cannot_be_above_50' => 'لايمكن أن تتجاوز نسبة الحسم 50%',
    'amount_cannot_be_above_100' => 'لايمكن أن تتجاوز نسبة الحسم 100%',
    'created_by' => 'أنشئ بواسطة',
    'confirm_membership_cancellation' => 'هل أنت متأكد الغاء الانتساب لهذا المستخدم؟',
    'invalid_slot_time' => 'الوقت المحدد للمكالمة غير مقبول لأنه إما مضى بالفعل أو قريب جداً من الوقت الحالي حيث يجب أن يكون زمن المكالمة بعد 5 دقائق على الأقل من الوقت الحالي, حدد وقتاً آخر',
    'end_time_must_greater' => 'المجال المحدد غير مقبول .. يجب أن يكون وقت البداية أكبر من وقت النهاية',
    'donations' => 'التبرعات',
    'donated_call_stats' => 'حالة المكالمات المتبرّع بها',
    'donated_workshop_stats' => 'حالة الجلسات المتبرّع بها',

    'balance' => 'الرصيد',
    'wallet_balance' => 'رصيد المحفظة',
    'wallets' => 'المحفظات',
    'all_wallets' => 'جميع المحفظات',
    'bank_info' => 'معلومات البنك(اسم المستفيد/رقم الحساب)',
    'is_paid_for_advisor' => 'السداد لمقدم الخدمة',
    'is_paid_yes' => 'مسدد',
    'is_paid_no' => 'غير مسدد',
    'fees' => 'الرسوم',
    'withdraw' => 'سحب',
    'profits_withdrawal' => 'سحب الأرباح',
    'profits_withdrawal_request' => 'طلب سحب الأرباح',
    'profits_withdrawal_amount' => 'المبلغ المطلوب للحسب',
    'profits_withdrawal_note1' => '(الحد الأدنى للسحب (:min) ريال سعودي)',
    'profits_withdrawal_note2' => 'تأكد من رفعك لوثيقة العمل الحر ضمن حسابك وذلك يتم قبول الطلب',
    'profits_below_threshold' => 'أرباحك حاليًا أقل من الحد الأدنى للسحب',
    'balance_exceeded' => 'لايمكن سجب مبلغ أكبر من الرصيد الحالي',
    'cannot_proceed_without_freelance_document' => 'يرجى رفع وثيقة عمل حر أولاً لكي تتمكن من إتمام عملية السحب, لرفع الوثيقة أذهب لحسابك',
    'wallet_balance_exceeded' => 'رصيد المحفظة غير كافي',
    'withdrawal_request_added' => 'تمت إضافة طلب السحب بنجاح، في انتظار موافقة المشرف حتى يصبح قابلاً للمعالجة',
    'already_have_active_request' => 'لايمكن إرسال طلب سحب جديد, لديك طلب نشط مسيثاًً',
    'admin_notes' => 'ملاحظات الإدارة',
    'wallet_transactions' => 'تفاصيل العمليات المالية',
    'withdrawal_requests' => 'طلبات سحب الأموال',
    'withdrawal_amount' => 'المبلغ المراد للسحب',
    'withdrawal_status' => 'حالة الطلب',
    'freelance_document' => 'وثيقة العمل الحر',
    'download_freelance_document' => 'تحميل وثيقة العمل الحر',
    'withdrawal_amount_required' => 'المبلغ المراد للسحب مطلوب',
    'freelance_document_required' => 'وثيقة العمل الحر مطلوبة',
    'financial_department' => 'القسم المالي',
    'withdrawal_status_pending' => 'قيد الانتظار',
    'withdrawal_status_approved' => 'تم الموافقة عليه',
    'withdrawal_status_processing' => 'قيد المعالجة',
    'withdrawal_status_completed' => 'مكتمل',
    'withdrawal_status_rejected' => 'مرفوض',
    'withdrawal_status_cancelled' => 'ملغى',
    'withdrawal_request_processing' => 'معالجة طلب سحب الأرباح',
    'click_here' => 'من هنا',
    'changing_withdrawal_request_status_impossible' => 'لايمكن تغيير حالة طلب سحب أموال مكتمل',
    'wallet_balance_insufficient' => 'رصيد المحفظة غير كافي لإتمام هذه الطلب',
    'to_issue_freelance_doc' => 'لإصدار وثيقة العمل الحر',
    'enter_bank_info' => 'أدخل معلوماتك البنكية بشكل كامل',
    'total_pending' => 'قيد الأنتظار',
    'transaction_amount' => 'المبلغ المدفوع',
    'total_withdrawn' => 'إجمالي المسحوب',
    'to_review_your_freelance_doc' => 'لمعاينة الوثيقة التي تم رفعها سابقاً',
    'contact_with_us' => 'تواصل معنا في حال واجهتك مشكلة ما',
    'commissions' => 'العولات',
    'entity_name' =>  "المؤسسة",
    'advisor_name' =>  "المستشار",
    'entity_commission' =>  "نسبة المؤسسة",
    'advisor_commission' =>  "نسبة المستشار",
    'select_an_advisor' => 'اختر مستشار',
    'add' => 'إضافة',
    'min_entity_commission_invalid' => 'القيمة الصغرى لعمولة المؤسسة هي (min:)',
    'max_entity_commission_invalid' => 'القيمة الكبرى لعمولة المؤسسة هي (max:)',
    'min_advisor_commission_invalid' => 'القيمة الصغرى لعمولة المستشار هي (min:)',
    'max_advisor_commission_invalid' => 'القيمة الكبرى لعمولة المستشار هي (max:)',
    'profits_proceed' => 'ريع الأرباح',


];
