<?php

return [
    'sign_in' => "Sign In",
    'sign_up' => "Sign Up",
    'logout' => "Logout",

    // Common
    'tweets' => "Tweets",
    'field_required' => "This field is required",
    'sub_specialties_values' => "Please select valid sub specialties",
    'submit' => 'Submit',
    'save' => 'Save',
    'send_request' => 'Send a request',
    'posting' => 'Posting...',
    'post' => 'Post',
    'image' => 'Image',
    'no_tweets' => "No tweets found",
    'error' => "Error",
    'delete' => 'Delete',
    'success' => "Success",
    'failed' => "Failed",
    'view_all' => "View all",
    'follower' => "Followers",
    'followers' => "Followers",
    'following' => "Following",
    'more' => "More",
    'loading' => 'Loading...',
    'none' => "None",
    'male' => "Male",
    'female' => "Female",
    'username' => "Username",
    'usernames' => "Username",
    'name' => "Full name",
    'email' => "Email",
    'phone' => "Mobile (BusinessCard Number)",
    'password' => "Password",
    'confirm_password' => "Confirm Password",
    'phone_description' => "Please enter your number linked to the WhatsApp program for the purpose of sending a reminder of the dates of your reservations on the platform (the number will be invisible to users)",
    'gender' => 'Gender',
    'dob' => "Date of birth",
    'country' => "Country",
    'city' => "City",
    'specialties' =>  "Specialties",
    'entity_specialties' =>  "Entity Specialities",
    'sub_specialists' =>  "Sub Specialties",
    'sub_specialties' =>  "Sub Specialties",
    'specialty' => "Specialty",
    'general' => "General",
    'about' => "Bio",
    'timeline' => "Posts",
    'post' => "Post",
    'posts' => "Posts",
    'snapchat' => "Snapchat",
    'linkedin' => "LinkedIn",
    'insta' => "Instagram",
    'youtube' => "Youtube",
    'facebook' => "Facebook",
    'telegram' => "Telegram",
    'twitter' => "Twitter",
    'whatsapp' => "BusinessCard",
    'website' => "Website",
    'workshops' => "Tele-sessions",
    'current' => "Ongoing",
    'ongoing' => 'Ongoing',
    'not_started' => "Not Started",
    'canceled' => 'Canceled',
    'completed' => "Completed",
    'hold' => "On Hold",
    'unhold' => "Unhold",
    'this_minutes' => "(:minute) minutes",
    'participants' => "Participants",
    'no_data' => "No data available",
    'advisor' => "TeleIn Services",
    'beneficiary' => "Beneficiary",
    'beneficiary_name' => "Beneficiary Name",
    'beneficiary_account_number' => "Beneficiary Account Number",
    'checkout' => "Checkout",
    'fill_form' => "Please fill the form first.",
    'close' => "Close",
    'requests' => "Requests",
    'accept' => "Accept",
    'decline' => "Decline",
    'accepted' => "Accepted",
    'declined' => "Declined",
    'are_you_sure' => "Are you sure?",
    'yes' => "Yes",
    'no' => "No",
    'start' => "Start",
    'cancel' => "Cancel",
    'started' => "Started",
    'stop' => "Stop",
    'expired' => "Expired",
    'mark_complete' => "Mark Completed",
    'calls' => "Tele-calls",
    'back_to_home' => "Back to home",
    'back_to_outgoing_sessions' => "Back to outgoing sessions",
    'date' => "Date",
    'time' => "Time",
    'price' => "Price",
    'charities' => "Charities",
    'from' => "From",
    'to' => "To",
    'c_price' => "(:p)SR",
    'c_price_earning' => "(:p)<small>SR</small>",
    'coupon_discount' => "Coupon Discount",
    'subtotal' => "Total",
    'vat_full' => "Vat",
    'platform_fees' => "Platform Fee",
    'total' => "Total",
    'total_plus_vat' => "Total + fees",
    'tracker' => "Tracker",
    'invite_free' => "But, you have been invited to join free",
    'vat' => "Vat ((:vat)%)",
    'skip' => "Skip",
    'previous' => "Previous",
    'next' => "Next",
    'id' => "Id",
    'word' => "Word",
    'action' => "Action",
    'csv' => "CSV",
    'en_name' => "En Name",
    'ar_name' => "Ar Name",
    'created_at' => "Created At",
    'updated_at' => "Updated At",
    'coupon_code' => "Coupon Code",
    'type' => "Type",
    'maximum_use' => "Maximum Use",
    'expiry_date' => "Expiry Date",
    'amount' => "Amount",
    'fixed' => "Fixed",
    'percentage' => "Percentage",
    'text' => "Text",
    'status' => "Status",
    'no_of_request' => "No of request",
    'feed' => "Feed",
    'specialty_en_name' => "Specialty En Name",
    'specialty_ar_name' => "Specialty Ar Name",
    'ip' => "Ip",
    'page' => "Page",
    'user' => "User",
    'verification' => "Verification",
    'verified' => "Verified",
    'not_verified' => "Not Verified",
    'joined_at' => "Joined At",
    'last_active' => "Last Active",
    'subscriber' => "Subscriber",
    'admin' => "Admin",
    'dashboard' => "Dashboard",
    'edit' => "Edit",
    'users' => "Users",
    'feeds' => "Feeds",
    'settings' => "Settings",
    'coupons' => "Coupons",
    'all_coupons' => "All Coupons",
    'add_coupon' => "Add Coupon",
    'all_charities' => "All Charities",
    'add_charity' => "Add Charity",
    'blocked_words' => "Blocked Words",
    'all_words' => "All Words",
    'add_new_word' => "Add new word",
    'specialists' => "Specialists",
    'all_specialists' => "All Specialists",
    'add_new_specialists' => "Add new specialty",
    'all_sub_specialists' => "All sub Specialists",
    'add_new_sub_specialists' => "Add new sub specialty",
    'language' => "Language",
    'support' => "Support",
    'customer_support' => "Customer Support",
    'device' => "Device",
    'notifications' => "Notifications",
    'account_notifications' => 'Account Notifications',
    'search_history' => "Search History",
    'term' => "Term",
    'feeds-with-blocked-word' => "Feeds with blocked words",
    'reviews' => "Reviews",
    'review' => "Review",
    'zoom_call' => "Tele-call",
    'workshop' => "Tele-session",
    'workshop_by_title' => 'Workshop entitled',
    'star' => "Star",
    'send' => "Send",
    'messages' => "Tele-mails",
    'message' => "Tele-mail",
    'messaging' => "Tele-mails",
    'agree_terms_condition' => "I agree to the terms & conditions",
    'terms_condition' => 'Terms & Conditions',
    'answer' => "Answer",
    'answered' => "Answered",
    'you' => "You",
    'active' => "Active",
    'view' => "View",
    'book_now' => "Book Now",
    'already_participated' => "Already participated",
    'percentage_amount' => "Percentage amount",
    'fixed_amount' => "Fixed amount",
    'not_yet_rated' => "Not yet rated",
    'rate_service' => "Rate this service",
    'entity_type' => "Entity Type",
    'entity_status' => "Entity Status",
    'entity_name' =>  "Entity Name",
    'owner' => "Owner",
    'conversation' => "Conversation",
    'visit' => "Visit",
    'count' => "Count",
    'join' => "Join",    
    'import_charities' => "Import Charities",
    'creator' => "Creator",
    'first_message' => "First Tele-mails",
    'avg_rating' => "Average Rating",
    'filter' => "Filter",
    'all' => "All",
    'coupon' => "Coupon",
    'my_earnings' => "My Earnings",
    'ready_to_transfer' => "Ready to transfer",
    'workshop_reminder' => "Tele-session Reminder",
    'call_reminder' => "Tele-call Reminder",
    'explore' => "Explore",
    'order_accepted' => "Order Accepted",
    'order_rejected' => "Order Rejected",
    'invoice' => "Invoice",
    'approved' => "Approved",
    'incomplete' => "Incomplete",
    'pending' => "Not Started",
    'order' => "Order",
    'call' => "Tele-call",
    'bookings' => "Bookings",
    'initialized' => "Initialized",
    'billings' => "Billings",
    'reports' => 'Reports',
    'details' => "Details",
    'distribution' => "Distribution",
    'all_orders' => "All Orders",
    'payment_details' => "Payment Details",
    'admin_amount' => "Admin Amount",
    'transaction_id' => "Transaction id",
    'charity_advisor_amount' => "Charity/Advisor Amount",
    'reset' => "Reset",
    'deleted' => "Deleted",
    'search' => "Search",
    'trending' => "Trending",
    'hashtags' => "Hashtags",
    'category' => "Category",
    'follow' => "Follow",
    'unfollow' => "Unfollow",
    'order_created' => "Order Created",
    'forgot_password' => "Forgot Password",
    'select_speciality' => "Select Speciality",
    'select_sub_speciality' => "Select Sub Speciality",
    'verify_account' => "Verify Account",
    'done' => "Skip",
    'liked_tweets' => "Liked Tweets",
    'go_to_admin_panel' => "Go to admin panel",
    'invited' => "Invited",
    'order_id' => "Order Id",
    'select_charity' => "Options",
    'select_profit_proceed_type' => "Options",
    'conversation_completed' => "Conversation Completed",
    'logs' => "Logs",
    'submitting' => "Submitting",
    'workshop_canceled' => "Tele-session Canceled",
    'workshop_invited' => "Invited to Tele-session",
    'call_canceled' => "Tele-call Canceled",
    'conversation_canceled' => "Conversation Canceled",
    'call_reminder_subject' => "Tele-call reminder",
    'workshop_reminder_subject' => "Tele-session reminder",
    'workshop_completed' => "Tele-session Completed",
    'call_completed' => "Tele-call Completed",
    'my_workshops' => "Outgoing Tele-session Orders",
    'my_calls' => "Outgoing Tele-Call Orders",
    'set_my_call' => "Incoming Tele-Call Orders",
    'for_charity' => "For Charity",
    'not_for_charity' => "Not For Charity",
    'my_messages' => "Outgoing Tele-Mail Orders",
    'my_received_messages' => "Incoming Tele-Mail Orders",
    'join_workshop' => "Join Tele-session",
    'slot_not_available' => "Slot not available",
    'join_call' => "Join Tele-call",
    'reply_to_messages' => "Reply to Tele-mails",
    'confirmed_amount' => "Confirmed Amount",
    'system_logs' => "System Logs",
    'session_tracker' => "Session Tracker",
    'user_tracker' => "User Tracker",
    'total_amount' => "Total Amount",
    'final_amount' => "Final Amount",
    'gateway_amount' => 'Gateway amount',
    'charity' => "Charity",
    'transferred' => "Transferred",
    'home' => "Home",
    'example' => "Example",
    'transferred_to' => "Transferred to",
    'please_wait' => "Please wait",
    'not_paid' => "Not Paid",
    'payment_status' => "Payment Status",
    'find_more_workshops' => "Find more Tele-sessions",
    'my_following' => "My Following",
    'bank_details_name' => "Name: (:name)",
    'bank_details_account_number' => "Account Number: (:number)",
    'bank_details_bic_code' => "Account Number: (:bic)",
    'refund_initiated' => "Should refund",
    'refunded' => "Refunded",
    'media' => "Media",
    'suspended' => "Suspended",
    'remember_me' => "Remember Me",
    'payment_method' => "Payment Method",
    'export_csv' => "Export Csv",
    'my_workshop' => "Outgoing Tele-session Orders",
    'set_workshop' => "Incoming Tele-Session Orders",
    'account_number' => "Account Number",
    'is_expired' => "Is expired",
    'verify' => "Verify",
    'user_suspended' => 'Account suspended, Contact with the admin',
    'user_deactivated' => 'Account deactivated, Contact with the admin',


    // Outer home
    'welcome_title' => "Welcome to teleIn",
    'welcome' => "Welcome",
    'home_browse_specialty' => "Explore	professionals in your areas	of interest<br> You can	share your experiences and interests with everyone too",

    // Outer header
    'search_placeholder' => "Search for specialties or tweets..",
    'copyright' => "Copyright © (:date) teleIN. All rights reserved",

    // Outer auth
    'reset_here' => "Reset here",
    'forgot_password_auth' => "Forgot password?",
    'login_title' => 'Log in to account',
    'dont_have_account' => 'Don\'t have an account?',
    'register_now' => 'Register Now',
    'login' => "Login",
    'terms_register' => 'By clicking Register, you agree on our <a target="_blank" href="(:url)">terms and conditions.</a>',
    'already_have_account' => 'Already have an account?',
    'register' => "Register",
    'reset_password_heading' => "Reset your password",
    'change_mind' => "Changed your mind?",
    'change_password_heading' => "Reset your password",
    'otp' => "Enter OTP sent to your email",
    'verify_email_header' => "Verify Email",

    // Payment methods
    'visa' => "Visa",
    'stc' => "STC Pay",
    'free' => "Free",
    'apple' => "Apple",

    // Verify OTP page
    'resend_otp' => "Resend OTP",
    'otp_sent' => "OTP successfully sent",
    
    // Commented tweets
    'commented_tweets' => "Commented Tweets",

    // Message
    'message_expires_in' => "Expires within <span>(:time)</span>",

    'success_change_avatar' => "You have changed your avatar successfully",
    'success_change_cover' => "You have changed your cover successfully",
    
    // Error 404
    'page_not_available_404' => 'This page isn\'t available',
    'error_text_404' => 'The link may be broken, or the page may have been removed. Check to see if the link you\'re trying to open is correct.',
    
    // Breadcrumb
    'advisor_breadcrumb' => "Go To Advisor Panel",
    'beneficiary_breadcrumb' => "Go To Beneficiary Panel",
    
    // Dashboard
    'dashboard_search_placeholder' => "Search here by name",


    // Charity Beneficiary
    'b_name' => "Beneficiary Name",
    'b_account_number' => "Beneficiary Account Number",
    'bank_bic_code' => "Beneficiary BIC Code",
    'address_line_1' => "Address Line 1",
    'address_line_2' => "Address Line 2",
    'address_line_3' => "Address Line 3",
    
    // Forgot Password
    'check_email_otp' => "Please check your email for OTP",

    // To view full profile
    'view_full_profile' => 'To view full profile of this user you need to Sign In',
    
    // Explore
    'follow_best_advisors' => 'Explore users by specialty',
    'follow_best_entities' => 'Explore users by entities involved with us',



    // Blocked
    'account_currently_blocked' => 'Your account is currently blocked',
    'please_contact' => 'Please Contact ((:mail))' ,
    
    // Notifications
    'notification_feed.comment' => "<strong>(:name)</strong> commented on your feed",
    'notification_feed.like' => "<strong>(:name)</strong> liked your feed",
    'notification_follow' => "<strong>(:name)</strong> followed you",
    'notification_no_notifications' => "No notifications found.",
    'notification_no_orders' => "No orders found.",
    'notification_no_logs' => "No logs found.",
    'notification_message.accepted' => "<strong>(:name)</strong> has accepted your Tele-mail request.",
    'notification_message.rejected' => "<strong>(:name)</strong> has rejected your Tele-mail request.",
    'notification_message.completed' => "<strong>(:name)</strong> has answered your Tele-mail.",
    'notification_workshop.completed' => "<strong>(:name)</strong> has completed a Tele-session you participated.",
    'notification_workshop.canceled' => "<strong>(:name)</strong> has canceled a Tele-session",
    'notification_workshop.accepted' => "A Tele-session has been accepted",
    'notification_workshop.rejected' => "A Tele-session has been rejected",
    'notification_workshop.user_canceled' => "<strong>(:name)</strong> is canceled a Tele-session",
    'notification_call.completed' => "<strong>(:name)</strong> has completed a Tele-call you have reserved.",
    'notification_call.accepted' => "A Tele-call has been accepted",
    'notification_call.rejected' => "A Tele-call has been rejected",
    'notification_call.reminder' => "A Tele-call is about to begin",
    'notification_call.canceled' => "A pending Tele-call has been cancelled",
    'notification_call.user_canceled' => "<strong>(:name)</strong> is canceled a Tele-call",
    'notification_call_auto.canceled' => "A Tele-call has expired.",
    'notification_call.request' => "<strong>(:name)</strong> has sent you a Tele-call request",
    'notification_call.request.resolved' => "<strong>(:name)</strong> has added new Tele-call slots, click here to check and complete your booking",
    'notification_workshop.pending' => "<strong>(:name)</strong> has joined your Tele-session.",
    'notification_call.pending' => "<strong>(:name)</strong> has requested a Tele-call.",
    'notification_message.pending' => "<strong>(:name)</strong> has sent a Tele-mail request.",
    'notification_workshop.reminder' => "Tele-session is about to begin.",
    
    'notification_workshop.invited' => "<strong>(:name)</strong> has invited you to his Tele-session",
    'notification_workshop_auto.canceled' => "Tele-session has expired.",
    'notification_message.reminder' => "You have a pending Tele-mail",
    'notification_message.canceled' => "A Tele-mail request has been cancelled",
    'notification_message.user_canceled' => "<strong>(:name)</strong> is canceled a Tele-mail",

    // Notification content
    'notification_workshop_cancel_coupon' => "Sorry for inconvenience, next time you can use coupon <strong>(:coupon)</strong> to get a discount.",
    'notification_workshop_pending' => "Joined <strong>(:name)</strong>",
    'notification_workshop_reminder' => "<strong>(:name)</strong>",

    // Review Profile
    'review_profile_text' => " (:avg) out of 5 ( (:total) Reviews)",

    // Order cancel remarks
    'order_expired' => 'Order has expired',
    'order_advisor_canceled' => 'Order has been canceled by advisor',
    'order_admin_canceled' => 'Order has been canceled by admin',
    'order_admin_on_hold' => 'Order has been put on hold by admin',

    // Register Page
    'register_title' => "Create an account",        
    'your_interest' => "Your Interest:",
    'cred_wrong' => "Email/password combination is wrong",

    'username_unique' => "Username already exists",
    'username_limit' => "Username should be with in (:min) to (:max) chars long",
    'email_unique' => "Email already exists",
    'phone_unique' => "Phone already exists",
    'email_pattern' => "This should be a valid email address",
    'phone_pattern' => "This should be a valid phone number",

    'email_verification' => 'Email Verification',
    'account_verification' => 'Account Verification',

    'email_token_invalid' => 'Token is invalid.',
    'email_token_limit' => 'Token is invalid.',

    // Header
    'menu_hello' => "Hello, (:name)",
    'menu_edit_profile' => "Edit profile",
    'menu_edit_profile_desc' => "Modify your personal details.",
    'my_orders' => "My Orders",
    'reservation_requests' => "Pending Requests",
    'account_settings' => "Account Settings",
    'workshop_cant_create_alert' => 'To enable tele-session we need your complete profile details. Please <a href="(:url)" class="alert-link">complete your profile</a>. ( Social Links are optional )',

    // left side menu
    'saved_feed' => "Liked Tweets",
    'profile' => 'Profile',
    'advisor_desc' => "Go to advisor panel.",
    'beneficiary_desc' => "Go to beneficiary panel.",

    // Feed page
    'create_post' => 'Create Post',
    'feed_textarea_post_error_title' => 'Error',
    'create_workshop_desc' => 'Create your own Tele-session',

    'feed_textarea_empty' => 'You need to write something first to post it.',
    'feed_textarea_file_not_supported' => "Sorry, only (:supported) files are supported",
    'feed_char_limit_exceeded' => "Sorry, tweet cant not be more than (:limit) characters long.",
    'no_hashtag_found' => "No hashtag found",
    'no_category_found' => "No category found",
    'upcoming_messaging' => 'Upcoming Messaging',

    // Workshop form

    'workshop_already_booked' => "Tele-session already booked",
    'workshop_name' => "Tele-session Name",
    'workshop_description' => "Tele-session Description",
    'workshop_date' => 'Tele-session Date',
    'workshop_time' => 'Tele-session Time',
    'workshop_duration' => "Tele-session duration (In minutes)",
    'workshop_price' => "Price (The platform fee will be added to the total amount)",
    'workshop_capacity' => "Session Capacity",
    'workshop_charity' => "Charity (Optional)",
    'workshop_invite' => "Invite Advisor (Optional)",
    'workshop_name_required' => "Tele-session name is required",
    'workshop_name_max' => "Tele-session name should be with in (:max) chars long",
    'workshop_desc_required' => "Tele-session description is required",
    'workshop_date_required' => "Date is required",
    'workshop_time_required' => "Time is required",
    'workshop_duration_required' => "Duration is required",
    'workshop_duration_should_number' => "Duration should be only in minutes",
    'workshop_duration_invalid' => "Duration should be more than (:min)",
    'workshop_price_required' => "Price is required",
    'workshop_price_should_number' => "Price should be a number",
    'workshop_price_invalid' => "Price should be more than 0",
    'workshop_capacity_required' => "Session capacity is required",
    'workshop_capacity_should_number' => "Session capacity should be a number",
    'workshop_capacity_invalid' => "Minimum session capacity should be between (:min) and (:max)",        
    'workshop_invite_invalid' => "No user found with provided username",
    'workshop_invite_error_self' => "You cant not invite your self.",   
    'work_invite_cant_create'  => "You can not invite this user to Tele-session.",
    'workshop_join_expired' => "Sorry you can not join this Tele-session any more",
    'you_cant_use_this_time_for_workshop' => "Sorry this is the maximum capability available at this time, if you need more change the time",

    // workshop feed
    'workshop_feed_price' => "Book at (:price)SR",
    'workshop_feed_invited' => '<a href="(:profile_link)"><strong>@(:user)</strong></a> is invited to this Tele-session.',
    'workshop_feed_charity' => "Will be donated to&nbsp;(:charities)",
    'workshop_created' => "You have successfully created a new Tele-session",
    'feed_workshop_is_deleted' => "Sorry, this Tele-session is deleted",
    'feed_has_workshop' => "This feed has Tele-session <strong>(:name)</strong>",

    // feed Comment
    'comment_box_empty' => "Please write something in comment",
    'total_comments' => '(:num) comments',
    'load_more_comments' => 'Load more comments...',
    'write_comment' => 'Write down your comment....',
    'comment_box_max_limit' => "Sorry, comment can not be more than (:max) characters long.",

    //Feed options
    'delete_feed' => 'Delete',
    'delete_feed_desc' => 'Delete this tweet',

    // New feed notification
    'new_feed_available' => "New feed available",

    //Profile Page
    'follow_success' => "You are now following this user",
    'unfollow_success' => "You are no longer following this user",
    'error_while_uploading' => "Error while uploading image, try again.",
    'cover_not_supported' => "Sorry, only (:supported) files are supported",
    'change_cover' => "Change cover",
    'change_avatar' => "Change Avatar",
    'please_wait_cover' => "Please wait, while we are changing your cover photo.",
    'please_wait_avatar' => "Please wait, while we are changing your avatar.",
    'no_follower' => "No followers yet",        
    'no_following' => "Not following anyone",        
    'book_a_call' => "Book a Tele-call",
    'book_a_workshop' => "Book a Tele-session",
    'call_following_times_are_available' => "Following times are available",

    // edit Profile
    'general_information' => "Profile Information",
    'social_links' => 'Social Links',
    'social' => 'Social',
    'bank_details' => 'Bank Details (To receive your money)',
    'iban_number' => "IBAN Number",
    'about_bio_placeholder' => "Write your bio",
    'about_bio_placeholder_entity' => "Write your entity description",
    'bio' => "Bio",
    'about_achievements_placeholder' => "Write your achievements",
    'achievements' => "Achievements",
    'location' => "Country / City",
    'change_password' => 'Change Password',
    'current_password_not_match' => "Incorrect password.",
    'new_password_not_match' => "Not the same password.",
    'select_a_country' => "Select a country",
    'select_a_city' => "Select a city first",
    'enter_bank_details' => "Enter your bank details",
    'enter_beneficiary_name' => "Enter beneficiary name",
    'enter_account_number' => "Enter account number(IBAN)",
    'enter_bic_code' => "Enter bank BIC code",
    'enter_bank_name' => "Enter bank name",
    'current_password' => "Current password",
    'new_password' => "New password",
    'verify_password' => "Verify password",
    'phone_invalid' => "Please, enter a valid phone number",

    'snapchat_invalid' => "Enter a valid snapchat url",
    'linkedin_invalid' => "Enter a valid linked in url",
    'insta_invalid' => "Enter a valid instagram url",
    'youtube_invalid' => "Enter a valid youtube url",
    'facebook_invalid' => "Enter a valid facebook url",
    'telegram_invalid' => "Enter a valid telegram url",
    'twitter_invalid' => "Enter a valid twitter url",
    'website_invalid' => "Enter a valid website",

    // Workshop Page
    'create_workshop' => "Create Tele-session",
    'find_workshops' => "Find Tele-sessions",
    'find_workshops_search' => "Find Tele-sessions - (:filter)",
    'workshop_not_exists' => "Tele-session does not exists.",
    'capacity_exceed' => "Slots are full for this Tele-session",
    'workshop_request_expired' => "Tele-session request expired",
    'workshop_waiting_approval' => "Waiting for approvals",
    'workshop_join_not_started' => "Tele-session yet not started, keep trying or come back lated.",
    'workshop_join_preparing' => "Tele-session yet not started, keep trying or come back lated.",
    'workshop_join_completed' => "Tele-session is completed.",
    'workshop_join_canceled' => "Tele-session is canceled.",
    'workshop_cancel_placeholder' => "Insert a 100/100 coupon to cancel.",
    'search_workshop' => "Search Tele-session by name",

    // Calls
    'manage_calls' => "Manage Tele-calls",
    'find_calls' => "Find more Tele-calls",
    'find_calls_search' => "Find Tele-calls - (:filter)",
    'customize_calls' => "You can request a tele-call with (:filter)، please suggest three time you preferred then you will be notified when it’s confirmed",
    'booking_calls' => "You can book a tele-call with (:filter) from the available time scheduled as following",
    'create_call' => "Create a Tele-calling session",
    'back_to_manage_calls' => "Back to manage Tele-calls",
    'back_to_calls' => "Back to Tele-calls",
    'call_price' => "Price (The platform fee will be added to the total amount)",
    'call_slot_created' => "New Tele-call session is created",
    'call_request_created' => "Call request created! You will receive a notification as soon as the advisor approved it",
    'call_slots_available_for' => "Tele-call slot available for <strong>(:price) SR</strong> at <strong>(:time)</strong>",
    'call_request_expired' => "Tele-call request expired",
    'call_join_not_started' => "Tele-call yet not started, keep trying or come back lated.",
    'call_join_completed' => "Tele-call is completed.",
    'call_join_canceled' => "Tele-call is canceled.",
    'call_join_expired' => "Sorry, you can not join this Tele-call any more",
    'you_cant_use_this_time_for_call' => "Sorry, selected date and time is not free right now, please change date and time and try again.",
    'choose_suitable_appointments' => "Choose 3 suitable appointments for your call",
    'schedule_the_following_appointments' => "Please select the suitable time for you that been suggested by (<string>(:name)</string>) and name the price.",
    'schedule_the_following_appointments_note' => "“Please note that the time allowed for the tele-call is 15 minutes”",
    'call_request' => "Call request",
    'call_request_resolved' => "Your call request resolved",
    'date1' => "Date1",
    'date2' => "Date2",
    'date3' => "Date3",
    'schedule' => "Schedule",

    // Messaging
    'manage_message_price' => "Manage Tele-mails price",
    'back_to_messaging' => "Back to Tele-mails",
    'messaging_price_should_number' => "Price should be a valid number",
    'messaging_price_invalid' => "Price should be more than 0",
    'price_updated' => "Price updated",
    'message_modal_title' => "Send Tele-mail to (:name)",
    'enable_messaging' => "Enable Tele-mails",
    'write_your_message_first' => "Write your Tele-mail first",
    'book_message_for' => 'Book a Tele-mail for <strong>(:name)</strong>',
    'messaging_warning' => "If advisor did not Tele-mail you with in <strong>48 hours</strong> your payment will be refunded.",
    'conversation_request_expired' => "You can not accept this conversation any more its expired, will be removed soon.",
    'conversation_expired' => "Conversation is expired will be refunded soon",
    'write_answer' => "Write your answer",
    'warning_before_message_answer' => "Is this your final answer?",

    // Request

    //Review
    'review_title_conversation' => "How did you like the service of <strong>(:name)</strong>?",
    'review_title_workshop' => "How did you like the service of <strong>(:name)</strong>?",
    'review_title_call' => "How did you like the service of <strong>(:name)</strong>?",
    'give_your_rating' => "Give your rating and let other users know how was your experience",
    'is_final_review' => "Is this your final review?",
    'thank_you' => "Thank you for giving your review, it helps a lot.",

    // Service related
    'service_time_over' => "Sorry, service time is over, can not start any more",
    // 'service_time_yet_not_started' => "Sorry, you can start this service just before (:min) minutes",
    'service_join_advisor_not_started' => "Sorry, looks like advisor is late, please wait or if advisor not coming please contact support.",
    'service_time_yet_not_started' => "Sorry, you can only start this service when its time starts",
    'service_expire_reason' => "Sorry, the service time has expired. It will be automatically canceled within 24 hours and you will be refunded.",
    'not_service_owner' => "Oops, looks like you are not the service owner",

    // Checkout page
    'pay_with_apple_pay' => "Pay with Apple pay",
    'pay_with_visa' => "Pay with VISA / MASTER",
    'pay_with_mada' => "Pay with MADA",
    'pay_with_stc' => "Pay with STC PAY",
    'pay_now' => "Pay now (:price) SR",
    'check_out_for' => "Checkout for: (:name)",
    'free_checkout' => "Checkout for free",
    'checkout_invited_free_workshop' => "You have been invited to free join this Tele-session.",
    'checkout_success' => "Success",
    'checkout_fail' => "Failed",
    'order_success' => "Your order created successfully",
    'order_success_desc' => "Thank you, your order for the service is successful. Please checkout my order page for more details about the order.",
    'order_waiting_desc' => "Please wait a little while to ensure that the process is completed successfully",
    'order_fail' => "Oops! your have failed to create your order",
    'order_fail_desc' => "Looks like we could not process your payment",
    'go_to_my_orders' => "Go to my orders",
    'checkout_wait_preparing' => "Wait, while we are preparing for checkout. You will be redirected soon",
    'apply_coupon_btn' => "+ Apply coupon",
    'coupon_expired' => "Sorry, this coupon is now expired",
    'coupon_applied' => "Coupon <strong>(:coupon)</strong> is applied",
    'select_a_payment_option' => "Select a payment option",
    'checkout_pay_title' => "Complete your payment",
    'slot_full' => "Sorry, this Tele-session is full.",
    'slot_full_badge' => "Slot full",
    'checkout_workshop_expired' => "This Tele-session can not be booked any more as time is expired.",
    'checkout_call_expired' => "This Tele-call can not be booked any more as this expired.",

    // Coupons
    'total_use_count' => "Total use count: (:count)",
    'coupon_not_found' => "This coupon does not exist, please enter a valid one",
    'coupon_max_limit_reached' => "Sorry, this coupon has reached its max use limit",
    'coupon_100_required' => "Sorry, you need to add a 100/100 coupon to invite",

    // Invite        
    'invite_user_desc' => "Please use comma separator to invite users. Eg: @username1, @username2",
    'invite_free_users' => "Invite free users",
    'invite_free_user' => "Invite free user",
    'invite_error_self' => "Sorry you cant not invite your self.",
    'invite_error_not_found' => "Sorry, some of the users are not found.",
    'invite_successful' => "Invited successfully",
    
    // Order page
    'order_request_for_workshop' => 'This user requested Tele-session entry for <strong>(:name)</strong>.',
    'order_request_for_call' => 'This user requested a Tele-call on <strong>(:name)</strong>.',
    'order_request_for_conversation' => 'This user booked a Tele-mail, <strong>(:name)</strong>.',

    // My order
    'my_orders_title' =>  "Total <strong>(:count)</strong> orders",
    'ordered_on' => 'Ordered on <strong>(:date)</strong> at <strong class="text-info">(:price)SR</strong>',
    'your_order_id' => "Order Id #(:id)",
    'user_cant_cancel_anymore' => "This order can not be canceled any more",

    // View order page
    'ordered_on_view' => 'Ordered on <strong>(:date)</strong>',
    'payment_initiated_on_view' => ' Payment initiated at (:date) for <strong>(:price)SR</strong>',

    // Logs
    'earning_log_order_declined' => 'A (:entity_type) order is canceled. should refund amount (:amount)SR <a href="(:link)">View Order</a>',
    'earning_log_order_accepted' => 'A (:entity_type) order is accepted for (:amount)SR <a href="(:link)">View Order</a>',
    'earning_log_order_pending' => '(:userLink) has ordered a new (:entity_type) <a href="(:link)">View Order</a>',
    'earning_log_order_canceled' => 'An (:entity_type) order is canceled, should refund amount (:amount)SR <a href="(:link)">View Order</a>',
    'earning_log_order_completed' => 'An (:entity_type) order is completed of amount (:amount)SR <a href="(:link)">View Order</a>',

    // Search 
    'whats_trending' => "Whats trending",
    'searching_for' => "Searching for \"(:term)\"",
    'no_search_term' => "No search term provided",

    // Instruction modal
    'instruction_header' => "Instructions",

    // Email subjects
    'support_email_title' => "You have got new email from (:email)",

    // Admin billing
    'change_status' => "Change Status",
    'order_status_change_warning' => "Once you change the status to <strong>cancel</strong> you can not go back. So, choose wisely.",

    // New version changes
    'privacy_policy' => 'Privacy Policy',
    'terms_of_use' => 'Terms of use',
    'view_personal_profile_details' => "View personal profile details",
    'manage_your_account_parameters' => "Manage your account parameters",
    'sign_out' => "Sign out",
    'write_something_here' => 'Write something here...',

    'c_views' => '(:num) Views',
    'c_likes' => '(:num) Likes',
    'view_more_request' => 'View More Request',
    'cancelled_expired' => 'Cancelled/Expired',
    'stats' => 'Stats',
    'message_stats' => 'Message Stats',
    'call_stats' => 'Call Stats',
    'workshop_stats' => 'Workshop Stats',
    'block' => 'Block',
    'unblock' => 'Unblock',
    'please_upload_csv' => 'Please upload a csv file',
    'please_upload_jpg_png' => 'Please upload either a jpg or png file',
    'please_select_a_img' => 'Please select a image',
    'view_image' => 'View Image',
    'personal_improvement' => 'Personal Improvement',

    'call_duration_details' => 'Every call duration is (:duration) minutes long',
    'search_more_workshop' => "Search more Tele-session by name",    
    'back_to_my_account' => "Back to my account",
    'entity_id' => "Entity Id",
    'ref_id' => "Ref: (:id)",
    'ref' => "Ref",
    'share' => "Share",

    'my_profile' => "My profile",
    'header_my_messages' => "My Tele-Mails",
    'header_my_calls' => "My Tele-Calls",
    'header_my_workshops' => "My Tele-Session",

    'feed_sure' => 'Are you sure want to delete this feed?',

    'explore_professionals_interest' => 'Explore professionals in you areas of interest',
    'share_experience_interest' => 'You can share your	experiences	and	interests with everyone	too',

    // New changes
    'likes' => 'Likes',
    'comments' => 'Comments',
    'close_modal' => "Close",
    'filter_workshop' => "Search",
    'following_profile' => "Following",
    'find_more_workshops_nav' => "Book Tele-Session",
    'header_my_workshops_nav' => "My Tele-Sessions",
    'workshop_min_time_error' => "Time must be equal or greater than (:min)",
    'already_scheduled_workshop' => "Cross sessions cannot be created, You have already a workshop will start in (:date), Choose another period!",

    // Instruction
    'instruction_header' => 'Welcome to TeleIn social media communication',

    'instruction_desc_1' => 'You can invest your time by sharing your experiences and expertise with others in any field or specialty, whether it is education, technology, entertainment or even discuss general ideas, cultures or whatever is trending',
    'instruction_desc_2' => 'TeleIn will allow you to receive calls, messages, and even create sessions that may increase your monthly income.At the same time, you can also request calls, send messages, or book sessions with others and socialize with anyone through our website',
    'instruction_desc_3' => 'TeleIn is a website that can increase your monthly income and facilitate your communications and socialization with others',

    'faq' => 'FAQS',
    'terms_of_service' => 'Terms of Service',
    'change_language' => "Click to change the language",

    'after_deducting_service_fee' => "After deducting service fee",

    // Waiting room
    'waiting_room' => 'Waiting room',
    'waiting_for_host_to_start_this_session' => 'Waiting for the host to start this tele-session',
    'waiting_for_host_to_start_this_call' => 'Waiting for the host to start this tele-call',
    'time_remaining_to_start_session' => 'The time remaining to start this tele-session is:',
    'time_remaining_to_start_call' => 'The time remaining to start this tele-call is:',
    'waiting_for_the_host_to_start_the_session' => 'Waiting for the host to start this tele-session',
    'waiting_for_the_host_to_start_the_call' => 'Waiting for the host to start this tele-call',
    'you_have_session_with_advisor' => 'You have a tele-session with:',
    'you_have_session_with_participant' => 'Your tele-session is about to begin soon',
    'you_have_call_with_advisor' => 'You have a tele-call with:',
    'you_have_call_with_participant' => 'Your tele-call is about to begin soon',

    // WhatsApp notifications
    "workshop_booked" => 'You have successfully registered to attend the session under :workshop_title
We will send a link to attend this session 15 minutes before its time here and via e-mail
To add an appointment and session details to the calendar, click here',

    'value_greater_than' => 'The value should be greater than (:value)',
    'value_less_than' => 'The value should be less than (:value)',

    'individual' => 'Individual',
    'entity' => 'Organization / Charity / Foundation / GOV',
    'entities' => 'Entities',
    'all_entities' => 'All entities',
    'add_entity' => 'Add entity',
    'your_entity' => 'Your entity',
    'select_an_entity' => 'Choose one of the entities participating in the Telein platform',
    'associates_profile' => 'Associates',
    'no_associate' => 'No associates yet',
    'associates' => 'Associates',

    'order_status' => 'Booking order status',
    'service_status' => 'Service Status',
    'service_type' => 'Service Type',
    'service_name' => 'Service Name',
    'select_a_user' => 'Select a user',
    'select_workshop' => 'Select a workshop',

    'inv_title' => 'Participation invoice',
    'inv_company_title' => 'Tele-in Platform',
    'inv_registration_no' => 'Registration Number',
    'inv_invoice_to' => 'Invoice to',
    'inv_invoice_no' => 'Invoice No',
    'inv_invoice_date' => 'Invoice Date',
    'inv_sum' => 'Sum',
    'inv_qty' => 'Qty',
    'inv_fee' => 'Fee',
    'inv_platform_fee' => 'Platform Fee',
    'inv_vat' => 'Vat',
    'inv_description' => 'Desc',
    'inv_item' => 'Item',
    'inv_total' => 'Total',
    'inv_paid' => 'Paid',
    'inv_amount_due' => 'Due amount',
    'inv_discount_percentage' => 'Discount',



    'notification_workshop_about_to_start' => "Your session (:title) with (:name) will start in 15 minutes",
    'notification_call_about_to_start' => "Your tele-call with (:name) will start in 5 minutes",

    'incoming_notification' => 'Incoming notification',

    'Sat' => 'Sat',
    'Sun' => 'Sun',
    'Mon' => 'Mon',
    'Tue' => 'Tue',
    'Wed' => 'Wed',
    'Thu' => 'Thu',
    'Fri' => 'Fri',

    'thanks_for_contacting_with_us' => 'Thank you for contacting us. Your message will be considered as soon as possible',
    'options' => 'options',
    'profit_for' => 'Profits for',
    'available' => 'Available',
    'single_slot' => 'Single slot',
    'many_slots' => 'Many slots',
    'from_time' => 'From',
    'to_time' => 'To',
    'no_results' => 'No results',
    'cropper_modal_title' => 'Crop photo',
    'amount_cannot_be_above_50' => 'The discount percentage must not exceed 50%',
    'amount_cannot_be_above_100' => 'The discount percentage must not exceed 100%',
    'created_by' => 'Created by',
    'confirm_membership_cancellation' => 'Are you sure you want to cancel the membership of this user?',
    'invalid_slot_time' => 'The specified time for the call is not acceptable because it has either already passed or is very close to the current time. The call time should be at least 5 minutes later than the current time. Please select another time',
    'end_time_must_greater' => 'The specified range is not acceptable. The start time must be greater than the end time.',
    'donations' => 'Donations',
    'balance' => 'Balance',
    'wallet_balance' => 'Wallet Balance',
    'wallets' => 'اWallets',
    'all_wallets' => 'All Wallets',
    'bank_info' => 'Bank Info(Beneficiary/Account)',
    'is_paid_for_advisor' => 'Advisor payment status',
    'is_paid_yes' => 'Paid',
    'is_paid_no' => 'Not Paid',
    'fees' => 'Fees',
    'withdraw' => 'Withdraw',
    'profits_withdrawal' => 'Profits withdrawal',
    'profits_withdrawal_request' => 'Profits withdrawal request',
    'profits_withdrawal_amount' => 'The amount required for calculation',
    'profits_withdrawal_note1' => '(The minimum withdrawal amount is (:min) R.S)',
    'profits_withdrawal_note2' => 'Make sure that you upload the freelance work document to your account and the application will be accepted',
    'profits_below_threshold' => 'Your profits are currently below the minimum threshold for withdrawal',
    'balance_exceeded' => 'It is not possible to withdraw an amount greater than the current balance',
    'cannot_proceed_without_freelance_document' => 'Please upload a freelance document first so that you can complete the withdrawal process. To upload the document, go to your account',
    'wallet_balance_exceeded' => 'The wallet balance is insufficient',
    'withdrawal_request_added' => 'Withdrawal request added successfully, waiting for admin approve to be processable',
    'already_have_active_request' => 'A new withdrawal request cannot be sent. You have an active request',
    'admin_notes' => 'Admin notes',
    'wallet_transactions' => 'Transactions',
    'withdrawal_requests' => 'Withdrawal requests',
    'withdrawal_amount' => 'Amount',
    'withdrawal_status' => 'Request status',
    'freelance_document' => 'Freelance document',
    'download_freelance_document' => 'Download freelance document',
    'withdrawal_amount_required' => 'Withdrawal amount is required',
    'freelance_document_required' => 'Freelance document is required',
    'financial_department' => 'Financial Department',
    'withdrawal_status_pending' => 'Pending',
    'withdrawal_status_approved' => 'Approved',
    'withdrawal_status_processing' => 'Processing',
    'withdrawal_status_completed' => 'Completed',
    'withdrawal_status_rejected' => 'Rejected',
    'withdrawal_status_cancelled' => 'Cancelled',
    'withdrawal_request_processing' => 'Withdrawal request processing',
    'click_here' => 'Click here',
    'changing_withdrawal_request_status_impossible' => 'The status of a completed withdrawal request cannot be altered.',
    'wallet_balance_insufficient' => 'Wallet balance insufficient',
    'to_issue_freelance_doc' => 'To issue a freelance document',
    'enter_bank_info' => 'Enter your banking information completely',
    'transaction_amount' => 'Amount',
    'total_withdrawn' => 'Total withdrawn',
    'to_review_your_freelance_doc' => 'Preview the previously uploaded document',
    'contact_with_us' => 'Contact with us',
    'commissions' => 'Commissions',
    'advisor_name' =>  "The advisor",
    'entity_commission' =>  "Entity commission",
    'advisor_commission' =>  "Advisor commission",
    'select_an_advisor' => 'Select an advisor',
    'add' => 'Add',
    'min_entity_commission_invalid' => 'القيمة الصغرى لعمولة المؤسسة هي (min:)',
    'max_entity_commission_invalid' => 'القيمة الكبرى لعمولة المؤسسة هي (max:)',
    'min_advisor_commission_invalid' => 'القيمة الصغرى لعمولة المستشار هي (min:)',
    'max_advisor_commission_invalid' => 'القيمة الكبرى لعمولة المستشار هي (max:)',
    'profits_proceed' => 'Profits proceeds',

];
